version: '3'

services:
    postgres:
        image: postgres:12
        restart: always
        container_name: postgresql
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: 123456
        ports:
            - 15432:5432
        volumes:
            - $HOME/postgres/data-db:/var/lib/postgresql/data
        networks:
            - postgres-network
    
    pgadmin:
        image: dpage/pgadmin4
        restart: always
        container_name: pgadmin4
        environment: 
            PGADMIN_DEFAULT_EMAIL: lassulfi@gmail.com
            PGADMIN_DEFAULT_PASSWORD: pgadmin
        ports:
            - 16543:80
        depends_on:
            - postgres
        networks:
            - postgres-network

networks:
    postgres-network:
        driver: bridge